export const cities = [
  "Alagoinhas",
  "Barreiras",
  "Bom Jesus da Lapa",
  "Brumado",
  "Camaçari",
  "Candeias",
  "Cruz das Almas",
  "Conceição do Coité",
  "Euclides da Cunha",
  "Eunápolis",
  "Feira de Santana",
  "Guanambi",
  "Ilhéus",
  "Ipiaú",
  "Irecê",
  "Itaberaba",
  "Itabuna",
  "Itapetinga",
  "Jacobina",
  "Jequié",
  "Juazeiro",
  "Paulo Afonso",
  "Porto Seguro",
  "Salvador",
  "Santo Amaro",
  "Santo Antônio de Jesus",
  "Senhor do Bonfim",
  "Simões Filho",
  "Teixeira de Freitas",
  "Valença",
  "Vitória da Conquista"
]
